name = 'shivam-blog'
license = 'MIT'
licenselink = 'https://github.com/imgios/not-much/blob/main/LICENSE'
description = 'A blog by Shivam Kushwaha'

homepage = 'https://github.com/imgios/not-much'

demosite = 'https://giosuesulipano.it/not-much/'

tags = ['blog', 'website', 'simple', 'dark', 'minimal', 'responsive']

features = ['blog', 'reponsive', 'theme-palettes']

[author]
name = 'Shivam Kushwaha'
homepage = 'https://giosuesulipano.it'
